/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const myMesh = useRef();
  const { nodes, materials } = useGLTF("../../laptop.glb");

  useEffect(() => {
    myMesh.current.geometry.translate(-1, 0, 0);
  });

  useFrame(({ clock }) => {
    myMesh.current.rotation.y = -clock.getElapsedTime();
    myMesh.current.translate(-1, 0, 0);
  });

  return (
    <group ref={myMesh} {...props} dispose={null}>
      <group
        position={[0, 0, -2]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.48, 0.2, 2.02]}
      >
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.019"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../laptop.glb");
